language: node_js
dist: trusty
sudo: false

cache:
  directories:
    - travis_phantomjs

# Upgrade PhantomJS to v2.1.1.
before_install:
  - npm i -g npm@latest-4
  - npm run bootstrap
  - "export PHANTOMJS_VERSION=2.1.1"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"

env:
  global:
    - CI_TEST="true"
    - CF_TEST="false"
    - START_TIMEOUT=20000
    - TOTAL_TIMEOUT=120000

matrix:
  include:
    - node_js: "8.9.4"
      env: DESCRIPTION="pouchdb"
    - node_js: "8.9.4"
      env:
        - DESCRIPTION="couchdb"
        - JOBS=1
        - DBCLIENT=abacus-couchclient
        - DB=http://localhost:5984
      services:
        - couchdb
    - node_js: "8.9.4"
      env:
        - DESCRIPTION="mongodb"
        - JOBS=1
        - DBCLIENT=abacus-mongoclient
        - DB=mongodb://localhost:27017
      services:
        - mongodb
      before_script:
        - sleep 15

install: echo "install"

script: yarn run build && yarn run generate-coverage && yarn run report-coverage

notifications:
  irc:
    use_notice: true
    on_success: change
    on_failure: change
    channels:
    - chat.freenode.net#cf-abacus
  slack:
    secure: ZanKYSBhluB1KMzd003+7PiASbgKKwNKl3Ucc4B3wuFWdpdNp/K4/AxPnjGTIRvFtyMtvHf+392bURxBWQMypyW+FMQXGOnJD+bVrVhzxAVc10smkT59NcemWry4gwHQlPF22MB+EoYqnsqXLFltMalEzRC+sjiXED7ZguUD7SJquRmydIlBHkU8hqbGwLg78oNS9WarhvikjsrKchNfSLe3pOMCspgpNQ4KAY+KdrUB4hAqlaul+WdUz3ivaazQZXtV4Rq9i9ADHh7WgyF1SYSWrqAQXuiM5KnwaD/m3lL01F9wxfK/NbuPH6gYg1XZhxhGBw4uT+udWZ3YFQy/G3YRu8URx1er+evI8JMhjjO+BIO1K3geEQ1Kmu1FdCeuhtbWVo0fokLkQGISVc0llgjIC1PR8NMMtDHTvUiK44F8GRONnT9tmKTyJBfRCwD23NV6oWPH2LL6uCya4CmveaKSz1G3IjulGGCdxCkIMjraw/J7fkg8INc9lhEl8Uim7pIJkDjuNp8zf4AGOTUpX1O9RMMvQkWqmpkf4Gug/JFcMAiX1WEQ6/5M3Q3HBLW3fe2DEp1H+A9RakA/QMGIytFm9oAnUGhad20wmvPlAaWxY+UpLHH/VNx7X5k/DhygSKnORuHLuR821LXCuLROEh5dtxdZckxXWFJH11xXhlw=
